title: emilybrooks
url: "https://emilybrooks.github.io"
markdown: kramdown
kramdown:
    hard_wrap: true

remote_theme: pmarsceill/just-the-docs@v0.10.1 # before they started changing the theme

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: false

# Enable or disable heading anchors
heading_anchors: true

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

callouts_level: quiet
callouts:
  note:
    title: Note
    color: purple
  battle:
    color: blue
  menu:
    color: green
  items:
    title: Collect
    color: yellow

# External navigation links
nav_external_links:
  - title: Github
    url: http://github.com/emilybrooks
    hide_icon: false 
    opens_in_new_tab: false

  - title: Youtube
    url: http://youtube.com/@EmilyBrooksSpeedruns/videos
    hide_icon: false 
    opens_in_new_tab: false

  - title: Twitch
    url: http://twitch.tv/emilybrooks
    hide_icon: false 
    opens_in_new_tab: false

  - title: Bluesky
    url: http://bsky.app/profile/brooksemily.bsky.social
    hide_icon: false 
    opens_in_new_tab: false
  